"""Reference cycling physics package for the YetAnotherCyclingSim project."""

from .braking import BrakingForceDemand, braking_force_demand
from .corner_braking import (
    CornerBrakingStepResolution,
    CornerBrakingStepResult,
    resolve_corner_braking_step,
    step_simulation_with_corner_braking,
)
from .corner_consequence import (
    CORNER_GEOMETRY_OUTCOME_CLEAN,
    CORNER_GEOMETRY_OUTCOME_CONTROLLED_SLIP,
    CORNER_GEOMETRY_OUTCOME_WIDE_LINE,
    CornerGeometryConsequence,
    resolve_corner_geometry_consequence,
)
from .corner_technique import (
    RouteCornerTechniqueObservation,
    RouteCornerTechniqueScore,
    RouteCornerTechniqueSummary,
    score_route_corner_technique,
    summarize_route_corner_technique,
)
from .corner_consequence_application import (
    CornerConsequenceApplication,
    apply_corner_geometry_consequence,
)
from .corner_context import (
    CORNER_DIRECTION_LEFT,
    CORNER_DIRECTION_RIGHT,
    CORNER_DIRECTION_STRAIGHT,
    CornerContext,
    CornerContextSettings,
    corner_context_at,
)
from .corner_grip_demand import CornerGripDemand, corner_grip_demand
from .corner_limit import (
    CornerLateralLimit,
    corner_lateral_limit,
)
from .cornering import (
    CORNER_PHASE_APEX,
    CORNER_PHASE_APPROACH,
    CORNER_PHASE_ENTRY,
    CORNER_PHASE_EXIT,
    CORNER_PHASE_OUTSIDE,
    Corner,
    CornerConsequence,
    CornerProfile,
    CornerTechniqueAssessment,
    CornerTechniqueSample,
    CornerTechniqueSummary,
    apply_corner_exit_speed_mps,
    assess_corner_technique,
    classify_corner_grip_usage,
    corner_consequence_from_grip_usage,
    corner_grip_usage,
    corner_phase_at_distance,
    distance_to_corner_start_m,
    effective_friction_coefficient,
    maximum_corner_speed_mps,
    summarize_corner_technique,
)
from .grip_budget import SharedGripBudget, shared_grip_budget
from .grip_policy import (
    ResolvedSurfaceGrip,
    SurfaceGripPolicy,
    SurfaceGripRule,
)
from .model import (
    STANDARD_GRAVITY_MPS2,
    Environment,
    RiderInput,
    RiderParameters,
    SimulationState,
    aerodynamic_force_n,
    gravitational_force_n,
    road_angle_rad,
    rolling_resistance_force_n,
    step_simulation,
    step_simulation_with_brake_force,
    total_resistance_force_n,
)
from .route import RouteProfile, RouteSegment
from .road_physics import (
    RoadPhysicsProfile,
    RoadPhysicsSample,
    RoadPhysicsState,
    RoadPhysicsTransitionLimits,
)
from .sample_routes import ALPINE_CORNERS, ALPINE_JOURNEY, ALPINE_SURFACE_GRIP_POLICY, ALPINE_WEATHER
from .weather import WeatherKeyframe, WeatherProfile

__all__ = [
    "STANDARD_GRAVITY_MPS2",
    "BrakingForceDemand",
    "braking_force_demand",
    "RiderParameters",
    "Environment",
    "RiderInput",
    "SimulationState",
    "RouteSegment",
    "RouteProfile",
    "RoadPhysicsSample",
    "RoadPhysicsState",
    "RoadPhysicsTransitionLimits",
    "RoadPhysicsProfile",
    "WeatherKeyframe",
    "WeatherProfile",
    "SurfaceGripRule",
    "ResolvedSurfaceGrip",
    "SurfaceGripPolicy",
    "SharedGripBudget",
    "shared_grip_budget",
    "ALPINE_JOURNEY",
    "ALPINE_WEATHER",
    "ALPINE_SURFACE_GRIP_POLICY",
    "ALPINE_CORNERS",
    "CORNER_GEOMETRY_OUTCOME_CLEAN",
    "CORNER_GEOMETRY_OUTCOME_WIDE_LINE",
    "CORNER_GEOMETRY_OUTCOME_CONTROLLED_SLIP",
    "CornerGeometryConsequence",
    "resolve_corner_geometry_consequence",
    "CornerConsequenceApplication",
    "apply_corner_geometry_consequence",
    "RouteCornerTechniqueObservation",
    "RouteCornerTechniqueSummary",
    "RouteCornerTechniqueScore",
    "summarize_route_corner_technique",
    "score_route_corner_technique",
    "CORNER_DIRECTION_STRAIGHT",
    "CORNER_DIRECTION_LEFT",
    "CORNER_DIRECTION_RIGHT",
    "CornerContextSettings",
    "CornerContext",
    "corner_context_at",
    "CornerLateralLimit",
    "CornerGripDemand",
    "corner_grip_demand",
    "corner_lateral_limit",
    "Corner",
    "CornerProfile",
    "CORNER_PHASE_OUTSIDE",
    "CORNER_PHASE_APPROACH",
    "CORNER_PHASE_ENTRY",
    "CORNER_PHASE_APEX",
    "CORNER_PHASE_EXIT",
    "effective_friction_coefficient",
    "maximum_corner_speed_mps",
    "corner_grip_usage",
    "classify_corner_grip_usage",
    "corner_phase_at_distance",
    "distance_to_corner_start_m",
    "CornerTechniqueSample",
    "CornerTechniqueSummary",
    "summarize_corner_technique",
    "CornerTechniqueAssessment",
    "assess_corner_technique",
    "CornerConsequence",
    "corner_consequence_from_grip_usage",
    "apply_corner_exit_speed_mps",
    "road_angle_rad",
    "gravitational_force_n",
    "rolling_resistance_force_n",
    "aerodynamic_force_n",
    "total_resistance_force_n",
    "step_simulation",
    "step_simulation_with_brake_force",
]
