"""Reference cycling physics package for the YetAnotherCyclingSim project."""

from .cornering import (
    CORNER_PHASE_APEX,
    CORNER_PHASE_APPROACH,
    CORNER_PHASE_ENTRY,
    CORNER_PHASE_EXIT,
    CORNER_PHASE_OUTSIDE,
    Corner,
    CornerConsequence,
    CornerProfile,
    CornerTechniqueAssessment,
    CornerTechniqueSample,
    CornerTechniqueSummary,
    apply_corner_exit_speed_mps,
    assess_corner_technique,
    classify_corner_grip_usage,
    corner_consequence_from_grip_usage,
    corner_grip_usage,
    corner_phase_at_distance,
    distance_to_corner_start_m,
    effective_friction_coefficient,
    maximum_corner_speed_mps,
    summarize_corner_technique,
)
from .model import (
    STANDARD_GRAVITY_MPS2,
    Environment,
    RiderInput,
    RiderParameters,
    SimulationState,
    aerodynamic_force_n,
    gravitational_force_n,
    road_angle_rad,
    rolling_resistance_force_n,
    step_simulation,
    total_resistance_force_n,
)
from .route import RouteProfile, RouteSegment
from .sample_routes import ALPINE_CORNERS, ALPINE_JOURNEY, ALPINE_WEATHER
from .weather import WeatherKeyframe, WeatherProfile

__all__ = [
    "STANDARD_GRAVITY_MPS2",
    "RiderParameters",
    "Environment",
    "RiderInput",
    "SimulationState",
    "RouteSegment",
    "RouteProfile",
    "WeatherKeyframe",
    "WeatherProfile",
    "ALPINE_JOURNEY",
    "ALPINE_WEATHER",
    "ALPINE_CORNERS",
    "Corner",
    "CornerProfile",
    "CORNER_PHASE_OUTSIDE",
    "CORNER_PHASE_APPROACH",
    "CORNER_PHASE_ENTRY",
    "CORNER_PHASE_APEX",
    "CORNER_PHASE_EXIT",
    "effective_friction_coefficient",
    "maximum_corner_speed_mps",
    "corner_grip_usage",
    "classify_corner_grip_usage",
    "corner_phase_at_distance",
    "distance_to_corner_start_m",
    "CornerTechniqueSample",
    "CornerTechniqueSummary",
    "summarize_corner_technique",
    "CornerTechniqueAssessment",
    "assess_corner_technique",
    "CornerConsequence",
    "corner_consequence_from_grip_usage",
    "apply_corner_exit_speed_mps",
    "road_angle_rad",
    "gravitational_force_n",
    "rolling_resistance_force_n",
    "aerodynamic_force_n",
    "total_resistance_force_n",
    "step_simulation",
]
